[project]
name = "projeto-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "passlib>=1.7.4",
    "pytest>=9.1.1",
    "reflex>=0.9.11.post1",
    "sqlmodel>=0.0.42",
]


[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["."]
